def handler(msg):
   """
   Writes input argument back-out to the standard output returning input as 
   output.
   
   Generated by: `SQL Server Big Data Cluster`
   
   :param msg: The message to echo.
   :type msg: str
   :return:  The input message `msg` as output `out`.
   """
   print(msg)
   out = msg
   return out


if __name__ == '__main__':
    handler('Hello')