#' Writes input argument back-out to the 
#' standard output returning input as output.
#' 
#' Generated by: `SQL Server Big Data Cluster`
#'
#' @param msg A character message to echo.
#' @return The input \code{msg} as output \code{out}.
handler <- function(msg) {
   print(msg)
   out = msg   
   out
}
